#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys

config = {
    "fqdn": os.environ.get("BBS_FQDN", ""),
    "lets_encrypt": os.environ.get("BBS_LETS_ENCRYPT", "false").lower() == "true",
    "ssh_port": int(os.environ.get("BBS_SSH_PORT", "2222") or 2222),
}

json.dump(config, fp=sys.stdout)
